### ISSUE TITLE
为什么MarqueeWidget不能加入Column或者ListView里面

### ISSUE THREAD

**Issue by huaiguoguo** [baoolong/MarqueeWidget#6]
为什么MarqueeWidget不能加入Column或者ListView里面

还有就是有多行文字向左滚动， 并且有背景图片

![image](https://user-images.githubusercontent.com/1888094/64475561-008d6e80-d1b7-11e9-9497-978d574e35d0.png)

![image](https://user-images.githubusercontent.com/1888094/64475405-11d57b80-d1b5-11e9-940a-9dda0604c953.png)

![image](https://user-images.githubusercontent.com/1888094/64474832-f9f9f980-d1ac-11e9-9dff-cd1989ab3751.png)

![image](https://user-images.githubusercontent.com/1888094/64474878-8a383e80-d1ad-11e9-8cb5-31caf47741ef.png)

![image](https://user-images.githubusercontent.com/1888094/64474879-93c1a680-d1ad-11e9-95a7-7f60c2347187.png)

**Comment by baoolong** [comment]
因为我写的跑马灯本身就是一个ListView
